name: Build & Deploy app

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get CMake 4.0
        uses: lukka/get-cmake@latest
          
      - name: Verify CMake version
        run: cmake --version

      - name: Install emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Verify Emscripten
        run: |
          emcc -v
          emcmake cmake --version


      - name: Configure (Web Release)
        run: |
          emcmake cmake -B build_wasm \
            -DCMAKE_BUILD_TYPE=Release \
            -DOPENGL_VERSION="ES 3.0"


      - name: Build
        run: |
          cmake --build build_wasm -j$(nproc)


      - name: Prepare Pages files
        run: |
          mkdir -p dist
          cp build_wasm/*.html dist/
          cp build_wasm/*.js dist/
          cp build_wasm/*.wasm dist/
          cp build_wasm/*.data dist/
          mv dist/algo-visualizer.html dist/index.html


      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

